// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xebishysjkaqisulcylu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlYmlzaHlzamthcWlzdWxjeWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTM5NzMsImV4cCI6MjA2NDEyOTk3M30.ZZeoK-MnV79bzsztxgd-fACnBJtC37_oJ8K0YuXc6Wo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);